### ISSUE TITLE
Invalid Syntax Error.

### ISSUE THREAD

**Issue by shubham1520** [TobiasPankner/Teams-Auto-Joiner#1]
File "auto_joiner.py", line 14
    browser: webdriver.Chrome = None
           ^
SyntaxError: invalid syntax
![Screenshot (26)](https://user-images.githubusercontent.com/47914856/83111013-910f3480-a0e1-11ea-865c-d20c51187363.png)
This error is coming i have installed chrome drivers and even added the location in path folder!
![Screenshot (27)](https://user-images.githubusercontent.com/47914856/83111113-be5be280-a0e1-11ea-9304-938b0420bff9.png)

**Comment by TobiasPankner** [comment]
I think this is because you are using an older version of python. For the syntax in the error to work you need Python 3.6 or newer.

**Comment by dotrachit** [comment]
@TobiasPankner hey, i'm facing this issue even though i'm on `Python 2.7.16` and `selenium 3.141.0`

**Comment by TobiasPankner** [comment]
As I already stated above, you need python 3.6 or newer
