### ISSUE TITLE
The method for switching organizations has changed in Teams

### ISSUE THREAD

**Issue by oooooooooooooooo** [TobiasPankner/Teams-Auto-Joiner#107]
![image](https://user-images.githubusercontent.com/8386495/119244390-878f9f80-bb70-11eb-9a03-89269b811ded.png)

There's now another click before the organization can be switched

**Comment by oooooooooooooooo** [comment]
**Config File**
{
  "email": "",
  "password": "",

  "run_at_time": "",

  "meeting_mode": 2,
  "organisation_num" : 2,
  "random_delay": true,
  "check_interval": 120,

  "join_message": "",

  "auto_leave_after_min": 60,
  "leave_if_last": true,
  "leave_threshold_number": "3",
  "leave_threshold_percentage": "",
  "pause_search": true,

  "headless" : false,
  "mute_audio": true,
  "chrome_type": "google-chrome",

  "blacklist": [
    {
      "team_name": "Example Team 1",
      "channel_names": [
        "First Channel to blacklist in this team",
        "Second Channel to blacklist"
      ]
    },
     {
      "team_name": "Blacklist whole team",
      "channel_names": [
      ]
    }
  ],
  "blacklist_meeting_re": ""
}
 
**Dekstop**
OS: Windows 10
Browser: Tested on both Chrome and MSEdge
Version: Newest official stable builds for both (v90 64bit)

**Comment by oooooooooooooooo** [comment]
Able to manage with massive jank by just manually clicking very fast to change the organization before the "page is found".

**Comment by TobiasPankner** [comment]
Thanks for bringing this to my attention. I will create a fix for this shortly.

**Comment by oooooooooooooooo** [comment]
Thanks a ton for the quick reply! Sorry for the minor spam.

**Comment by TobiasPankner** [comment]
Fixed with commit e607b22
