### ISSUE TITLE
A few (potentially benign) errors in the command prompt including "Passthrough is not supported, GL is disabled" and "Failed to read descriptor from node connection"

### ISSUE THREAD

**Issue by oooooooooooooooo** [TobiasPankner/Teams-Auto-Joiner#108]
![image](https://user-images.githubusercontent.com/8386495/119244512-c7a35200-bb71-11eb-8fac-af1e6ff7432d.png)

**Comment by oooooooooooooooo** [comment]
**Config File**
{
"email": "",
"password": "",

"run_at_time": "",

"meeting_mode": 2,
"organisation_num" : 2,
"random_delay": true,
"check_interval": 120,

"join_message": "",

"auto_leave_after_min": 60,
"leave_if_last": true,
"leave_threshold_number": "3",
"leave_threshold_percentage": "",
"pause_search": true,

"headless" : false,
"mute_audio": true,
"chrome_type": "google-chrome",

"blacklist": [
{
"team_name": "Example Team 1",
"channel_names": [
"First Channel to blacklist in this team",
"Second Channel to blacklist"
]
},
{
"team_name": "Blacklist whole team",
"channel_names": [
]
}
],
"blacklist_meeting_re": ""
}

**Dekstop**
OS: Windows 10
Browser: Tested on both Chrome and MSEdge
Version: Newest official stable builds for both (v90 64bit)

**Comment by TobiasPankner** [comment]
These are browser errors. These are unrelated to the bot and (mostly) have no effect
