### ISSUE TITLE
Feature Request: Allow re-running of teams list generation and pausing of the script while it's running

### ISSUE THREAD

**Issue by oooooooooooooooo** [TobiasPankner/Teams-Auto-Joiner#109]
**Is your feature request related to a problem?**
Frequently had issues with switching organizations and getting the right list of teams. The feature for switching organizations is currently broken. In the past, as an interim method, when organizations switching wasn't built in and the feature was available I'd run the older version of the script, switch the organization manually, and then run the generation for the teams list. And then let the script run in the background. It was hacky, but it worked.

**Describe the solution you'd like**
As an interim and as additional security and troubleshooting the ability to re-run parts of the scrip and pause the script

**Describe alternatives you've considered**
I guess the ideal is that Microsoft stops messing with the UI but the very least this way if the organization switching is ever changed again or if there are additional steps added or removed the entire script doesn't break. The important parts can be re-run and specific stages can be done manually after pausing the script.

**Comment by TobiasPankner** [comment]
I understand what you mean. But this solution would be extremely messy to implement and would further complicate the code.  
For these reasons I think it is better to just update the bot whenever the UI updates.
