### ISSUE TITLE
little code for loading error of teams

### ISSUE THREAD

**Issue by H4D53** [TobiasPankner/Teams-Auto-Joiner#111]
Sometimes Microsoft Teams will fail on loading or initializing 
![error1](https://user-images.githubusercontent.com/47973426/119569693-aa74ba80-bde1-11eb-9b72-c1059d5b2aa2.png)
and I checked the information on Try again button
![error2](https://user-images.githubusercontent.com/47973426/119569765-c4160200-bde1-11eb-899c-63179dd12dae.png)

I think these code can be added / modified on line 618 (to line 625)
`    print("Waiting for correct page...", end='')

    if wait_until_found("#teams-app-bar", 60) is None:

        # click the Try again button if teams load error

        try_again = wait_until_found("button[class*='ts-btn ts-btn-primary oops-button']", 10)

        if try_again is not None:

            try_again.click()

        else:

            exit(1)

Hope this helps.

**Comment by TobiasPankner** [comment]
Great idea! Do you want to create a pull request and implement this yourself or should I add it?

**Comment by H4D53** [comment]
I am still a starter of Github, I have tried to pull request before I started this issue comment, but I failed, so could you please add it to your code. Thank you

**Comment by TobiasPankner** [comment]
Alright, thanks for the pictures and clear description. This is how every issue should be.

**Comment by H4D53** [comment]
> Alright, thanks for the pictures and clear description. This is how every issue should be.

I guess I have successfully pulled a request, please check it, thank you so much!
