### ISSUE TITLE
Organization switching requires adjustment due to the addition of another pop-up

### ISSUE THREAD

**Issue by oooooooooooooooo** [TobiasPankner/Teams-Auto-Joiner#113]
![image](https://user-images.githubusercontent.com/8386495/120265750-ee176a80-c2a0-11eb-875b-d93570f6f8e5.png)

Currently the program opens up teams to this screen when trying to switch the organization. The two briefcase lines in the image represent the two organizations.

Making it to this pop-up is not necessary to switching organizations but it's just what the program does right now.

**Comment by TobiasPankner** [comment]
What do you mean it's not necessary?

**Comment by oooooooooooooooo** [comment]
Very sorry for not being clear. If I quickly close out of this view and re-click the button on the top right to change the organization the program will do it's thing fine. But for some reason there's been a change in teams that makes this show up when letting autojoiner do its thing.

But "not necessary" I just meant that organization change does NOT have to go through this pop-up it can just go through the normal process.

**Comment by TobiasPankner** [comment]
Thank you for bringing this to my attention! Fixed with commit cc48850
