### ISSUE TITLE
opens chrome on new tab as guest instead of my google account

### ISSUE THREAD

**Issue by Paradox1610** [TobiasPankner/Teams-Auto-Joiner#114]
Hello,
when i run the bot, it opens the meeting on a fresh new chrome page which doesn't even have my google logged in ie; guest page. Is there any way i could set it in such a way that when it opens a fresh chrome tab, it must open the regular tab with my regular google logged in. I just want it to launch meeting in my usual chrome page, instead of fresh guest account page.
Thank you.

**Comment by TobiasPankner** [comment]
Sorry, this is not a feature. This is not implemented to prevent the bot from messing with other stuff in your browser and to keep settings the same for everyone.  
If you really need this you have to change the code.  
Why do you need it open in the existing browser?
