### ISSUE TITLE
"No module named 'selenium'" when running the script despite selenium installed

### ISSUE THREAD

**Issue by h3oCharles** [TobiasPankner/Teams-Auto-Joiner#119]
**Describe the bug**

when attempting to run the script, it fails and says that selenium is missing

**To Reproduce**
install python 380
download source zip and extract it to a folder
rename "config.json.example" to "config.json"
edit the config
run cmd inside the source directory
run "pip install -r requirements.txt"
run "python auto_joiner.py"
see the error
run "pip install selenium"
run "python auto_joiner.py" again
see the same error again

**Expected behavior**

the script would run

**Screenshots**

![image](https://user-images.githubusercontent.com/8020330/121524729-e326ad80-c9f7-11eb-8011-e7e6a669cccb.png)

**Configuration file**
Paste your configuration file here, without password and email. 

https://pastebin.com/mwFqBM9j

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 20H2 19042.985
 - Browser [e.g. chrome, safari] Google Chrome 91.0.4472.77 64 bit
 - Version [e.g. 22] ???
 - Python 3.8.0

**Additional context**

**Comment by h3oCharles** [comment]
pretty sure neither of the worked

![image](https://user-images.githubusercontent.com/8020330/121602118-1f352f00-ca47-11eb-98e7-7cbc9002640e.png)

**Comment by TobiasPankner** [comment]
And the pip3 command?

**Comment by h3oCharles** [comment]
oops sry

![image](https://user-images.githubusercontent.com/8020330/121657558-cb573400-caa0-11eb-84a6-23f92ba2e5ea.png)

**Comment by TobiasPankner** [comment]
Okay, first do the update it tells you to do. After that try running the program again. If it still doesn't work try `python3 auto_joiner.py`.  
If that also doesn't help try reinstalling python or maybe looking this problem up on the internet.  
Closing this issue because this is a problem with your pip/python, not with the bot.

**Comment by h3oCharles** [comment]
mind still helping out plz? pip is not a module now apparently

![image](https://user-images.githubusercontent.com/8020330/121773942-9077fd80-cb7f-11eb-8852-374c944bfd47.png)

**Comment by TobiasPankner** [comment]
There seems to be an issue that the python command uses an .exe in the Inkscape folder and not your real python installation. You probably need to change the PATH variable.

**Comment by h3oCharles** [comment]
yup, i had to remove the path for inkscape's python, that worked, thx

**Comment by TobiasPankner** [comment]
Great!
