### ISSUE TITLE
script crashes when discord webhook is empty...?

### ISSUE THREAD

**Issue by h3oCharles** [TobiasPankner/Teams-Auto-Joiner#121]
**Describe the bug**

after successfully solving the struggles from #119, now attempting to run the script 

**To Reproduce**
same stuff in #119, the solutions to it, then...
run auto_joiner.py
seems like it enters mail and password successfully
the page loads
after it loads, both browser and cmd closes
i make a bat file, containing this:
`python auto_joiner.py
pause`
run the bat file, same scenario, look at screenshot

**Expected behavior**

not sure tbh, maybe i'd see my teams page?

**Screenshots**

![cmd_ejGUI8USrt](https://user-images.githubusercontent.com/8020330/121819859-b55b9600-cc8f-11eb-9461-8863990cad74.png)

**Configuration file**
Paste your configuration file here, without password and email. 

same config file as in #119 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Pro 20H2 19042.985 64-bit
 - Browser [e.g. chrome, safari] Google Chrome Version 91.0.4472.101 (Official Build) (64-bit)
 - Version [e.g. 22] python 380

**Additional context**

i haven't tried setting up a webhook, should i? ive never done that before
feel free to edit title when relevant cause was found

**Comment by TobiasPankner** [comment]
Thanks for notifying me about this, fixed with commit c5d67af

**Comment by h3oCharles** [comment]
yup, after that fix the script is working as intended... whew, finally!
