### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ranveer90** [TobiasPankner/Teams-Auto-Joiner#122]
I get this error after doing steps in readme.md and running this 
error:
`Traceback (most recent call last):
  File "C:\Users\meenu\OneDrive\Desktop\TEAMSS\Teams-Auto-Joiner\auto_joiner.py", line 733, in <module>
    load_config()
  File "C:\Users\meenu\OneDrive\Desktop\TEAMSS\Teams-Auto-Joiner\auto_joiner.py", line 136, in load_config
    config = json.load(json_data_file)
  File "C:\Users\meenu\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\meenu\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\meenu\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\meenu\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 25 column 25 (char 495)
`
config.json:
`{
  "email": "",
  "password": "",

  "run_at_time": 19:51,

  "meeting_mode": 1,
  "organisation_num" : -1,
  "random_delay": true,
  "check_interval": 10,

  "join_message": "Joined the meeting",

  "auto_leave_after_min": 41,
  "leave_if_last": false,
  "leave_threshold_number": "7",
  "leave_threshold_percentage": "",
  "pause_search": false,

  "headless" : true,
  "mute_audio": false,
  "chrome_type": "google-chrome",

  "blacklist": [
    {
      "team_name": "Example Team 1",
      "channel_names": [
        "First Channel to blacklist in this team",
        "Second Channel to blacklist"
      ]
    },
     {
      "team_name": "Blacklist whole team",
      "channel_names": [
      ]
    }
  ],
  "blacklist_meeting_re": "",

  "discord_webhook_url" : "https://discord.com/api/webhooks/856883298054438953/1XmVsMGYhvC-uSkp1EVTJa0UEOQ0Y5WyxuiYmaoHNC7FaAt3g2IGTu36iMn4KQK8-q71"
}
`
Thanks

**Comment by TobiasPankner** [comment]
The 19:51 should be in quotes

**Comment by TobiasPankner** [comment]
The 19:51 should be in quotes

**Comment by Ranveer90** [comment]
the new json file:
`{
  "email": "",
  "password": "",

  "run_at_time": "08:40",

  "meeting_mode": 1,
  "organisation_num" : -1,
  "random_delay": true,
  "check_interval": 10,

  "join_message": "Joined",

  "auto_leave_after_min": 41,
  "leave_if_last": false,
  "leave_threshold_number": "7",
  "leave_threshold_percentage": "",
  "pause_search": false,

  "headless" : true,
  "mute_audio": true,
  "chrome_type": "google-chrome",

  "blacklist":
  "discord_webhook_url" : "https://discord.com/api/webhooks/856883298054438953/1XmVsMGYhvC-uSkp1EVTJa0UEOQ0Y5WyxuiYmaoHNC7FaAt3g2IGTu36iMn4KQK8-q71"
}

`

**Comment by Ranveer90** [comment]
> The 19:51 should be in quotes

yea u told me on reddit this is the new config file

**Comment by TobiasPankner** [comment]
But there the blacklist is completley wrong, change it to default or []

**Comment by Ranveer90** [comment]
> But there the blacklist is completley wrong, change it to default or []

i will try it 1 minute

**Comment by Ranveer90** [comment]
I still get this error:
`C:\Users\meenu\OneDrive\Desktop\TEAMSS\Teams-Auto-Joiner-master>python auto_joiner.py
Traceback (most recent call last):
  File "C:\Users\meenu\OneDrive\Desktop\TEAMSS\Teams-Auto-Joiner-master\auto_joiner.py", line 733, in <module>
    load_config()
  File "C:\Users\meenu\OneDrive\Desktop\TEAMSS\Teams-Auto-Joiner-master\auto_joiner.py", line 136, in load_config
    config = json.load(json_data_file)
  File "C:\Users\meenu\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\meenu\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\meenu\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\meenu\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 5 column 20 (char 93)`

**Comment by Ranveer90** [comment]
config is 
`{
  "email": "ranveer1293@sc1.krmangalam.com",
  "password": "Tot62908",

  "run_at_time": 19:51,

  "meeting_mode": 1,
  "organisation_num" : -1,
  "random_delay": true,
  "check_interval": 10,

  "join_message": "Joined the meeting :lollipop:",

  "auto_leave_after_min": 41,
  "leave_if_last": false,
  "leave_threshold_number": "7",
  "leave_threshold_percentage": "",
  "pause_search": false,

  "headless" : true,
  "mute_audio": false,
  "chrome_type": "google-chrome",

  "blacklist": [],
  "blacklist_meeting_re": "",

  "discord_webhook_url" : "https://discord.com/api/webhooks/856883298054438953/1XmVsMGYhvC-uSkp1EVTJa0UEOQ0Y5WyxuiYmaoHNC7FaAt3g2IGTu36iMn4KQK8-q71"
}
`

**Comment by TobiasPankner** [comment]
Put the 19:51 in quotes

**Comment by TobiasPankner** [comment]
And change your microsoft password because you just posted it online for everyone to see

**Comment by Ranveer90** [comment]
> And change your microsoft password because you just posted it online for everyone to see

changed the password and it worked!!!! tysm!!!! ur the best!!!!! can u delete the post and this issue so none sees the old password?

**Comment by TobiasPankner** [comment]
I don't I think I can delete an issue, sorry.
