### ISSUE TITLE
Help me to fix this problem

### ISSUE THREAD

**Issue by h0ay** [TobiasPankner/Teams-Auto-Joiner#123]
Setting up on centos 

![image](https://user-images.githubusercontent.com/63505168/124583425-a58b3800-de70-11eb-8439-a41f4551d6c0.jpeg)

Python version 3.6.8 facing this issue when launching the script 

Check the image

**Comment by TobiasPankner** [comment]
Apparently chrome is crashing. Make sure the browser is working correctly before starting the bot.

**Comment by h0ay** [comment]
How can i check that ?

**Comment by TobiasPankner** [comment]
I have no experience with this but just start Chrome and see what happens

**Comment by h0ay** [comment]
It's an vps

**Comment by TobiasPankner** [comment]
Run the chromium command then

**Comment by TobiasPankner** [comment]
Do you even have chronium installed?

**Comment by h0ay** [comment]
Only chrome is installed

**Comment by TobiasPankner** [comment]
Try with chromium, also be sure to change this in the config

**Comment by h0ay** [comment]
Okay

**Comment by h0ay** [comment]
What should i change it to in config ? google-chromium?

**Comment by TobiasPankner** [comment]
No, just `chromium`, read the Readme

**Comment by h0ay** [comment]
![image](https://user-images.githubusercontent.com/63505168/124612028-9ebfed80-de8f-11eb-9364-57de46900b30.jpeg)

**Comment by h0ay** [comment]
Fixed it myself thanks
Used my brain 

The problem was with the notification or a pop up which comes up after logging in so the script was clicking somewhere but the pop up was blocking the click 

Simple fix logged in my teams from a different computer browser and closed the pop up and with got it pop up 

And then started my vps again
