### ISSUE TITLE
Enable Video on Start

### ISSUE THREAD

**Issue by Bigben83** [TobiasPankner/Teams-Auto-Joiner#127]
Hi we use this auto joiner for scheduled Video Conferencing between offices every day
and would like it to start the video
can we use something in the config.json file to enable video. same was as you mute audio?

**Comment by TobiasPankner** [comment]
This is not a feature in the config, you can however edit the code to make this work.  
You have to comment out (or delete) the [lines 432 to 437](https://github.com/TobiasPankner/Teams-Auto-Joiner/blob/76132951bf16a6a02b23a0dbfbcaca48eb5d85be/auto_joiner.py#L432-L437).    
If you also want to enable the microphone you have to comment out the [lines 439 to 444](https://github.com/TobiasPankner/Teams-Auto-Joiner/blob/76132951bf16a6a02b23a0dbfbcaca48eb5d85be/auto_joiner.py#L439-L444).  
Make sure you are using the newest version.
