### ISSUE TITLE
Assignments Tab Opening by default

### ISSUE THREAD

**Issue by vaibhavvikas** [TobiasPankner/Teams-Auto-Joiner#13]
**Bug Description**
After configuring the config.json, when we run auto_joiner.py. It opens the assignment tab by default as a result it keeps on waiting on that screen and is unable to fetch team names and details etc. and throws the error Timeout waiting for element: .use-app-lnk. We have to manually click on the Teams tab to open our app.

**To Reproduce**
1. Configure the config.json
2. Run auto_joiner.py
3. After automatic login, the app keeps on waiting

**Expected behavior**
The app must open Teams tab and scan channels and teams automatically

**Screenshots**
![1](https://user-images.githubusercontent.com/28614457/91271062-3ac09900-e797-11ea-99f9-59c51a5a9723.JPG)
![2](https://user-images.githubusercontent.com/28614457/91271073-3d22f300-e797-11ea-99b3-5597bb02d8fd.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 20H2
 - Browser: Chrome
 - Version 84.0.4147

**Workaround.**
We have to click on the teams tab. Then the app scans the teams and we can join the meeting automatically

**Comment by vaibhavvikas** [comment]
I have submitted a PR for this issue 🙂

**Comment by TobiasPankner** [comment]
Fixed by merging your pull request fe2f080, and great issue by the way.
