### ISSUE TITLE
browser crashing/closing itself

### ISSUE THREAD

**Issue by glitchinventers1** [TobiasPankner/Teams-Auto-Joiner#132]
**Describe the bug**it joins a meeting and after a while it closes the browser and gives me a error

**To Reproduce**
just run the program and it will crash/give the error after a few mins

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/88477370/128807261-fefd3b01-aa16-4419-ac85-53c9e7a951b0.png)

**Configuration file**
{
  "email": "",
  "password": "",

  "run_at_time": "",

  "meeting_mode": 3,
  "organisation_num" : -1,
  "random_delay": true,
  "check_interval": 10,

  "join_message": "",

  "auto_leave_after_min": 0,
  "leave_if_last": true,
  "leave_threshold_number": "",
  "leave_threshold_percentage": "",
  "pause_search": true,

  "headless" : false,
  "mute_audio": true,
  "chrome_type": "google-chrome",

  "blacklist": [
    
  ],
  "blacklist_meeting_re": "",

  "discord_webhook_url" : ""
}

**Desktop (please complete the following information):**
 - win10
 - chrome
 - win - 20H2, chrome - 92.0.4515.131 (Official Build) (64-bit)

**Additional context**

**Comment by glitchinventers1** [comment]
forgot to say its also connected to a discord webhook

**Comment by glitchinventers1** [comment]
nvm i fixed myself

**Comment by TobiasPankner** [comment]
It was the thresholds right? Just so I can fix it for others.

**Comment by glitchinventers1** [comment]
i just commented the if and else statement out lmao
