### ISSUE TITLE
Failed to close meeting page

### ISSUE THREAD

**Issue by TobiasPankner** [TobiasPankner/Teams-Auto-Joiner#133]
![image](https://user-images.githubusercontent.com/71291013/130195071-da300593-3198-4bd3-8d28-d2e576187849.png)

_Originally posted by @DishantX in https://github.com/TobiasPankner/Teams-Auto-Joiner/issues/125#issuecomment-902487495_

**Comment by TobiasPankner** [comment]
Should be fixed with commit 4f83e6f

**Comment by DishantX** [comment]
It works now!
