### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by hanselsaji** [TobiasPankner/Teams-Auto-Joiner#144]
### Logs ### 

Ms-Teams-Auto-Joiner-Bot
Logged in successfully
Time: [2021:09:16-12:06:17]
login-id: 21p1052@christjuniorcollege.edu.in
Ms-Teams-Auto-Joiner-Bot
Timeout error
button.app-bar-link > ng-include > svg.icons-calendar
Time: [2021:09:16-12:06:38]
login-id: 21p1052@christjuniorcollege.edu.in
Ms-Teams-Auto-Joiner-Bot
Timeout error
.ms-CommandBar-secondaryCommand > div > button[class*='__topBarContent']
Time: [2021:09:16-12:06:45]
login-id: 21p1052@christjuniorcollege.edu.in
Ms-Teams-Auto-Joiner-Bot
No Teams found
is MS Teams in list mode? (switch to mode 3 if you only want calendar meetings)
Time: [2021:09:16-12:06:49]
login-id: 21p1052@christjuniorcollege.edu.in
Ms-Teams-Auto-Joiner-Bot
Browser closed
Thank you!
Time: [2021:09:16-12:06:52]
login-id: 21p1052@christjuniorcollege.edu.in
Ms-Teams-Auto-Joiner-Bot
Logged in successfully
Time: [2021:09:16-12:10:17]
login-id: 21p1052@christjuniorcollege.edu.in
Ms-Teams-Auto-Joiner-Bot
Timeout error
button.app-bar-link > ng-include > svg.icons-calendar
Time: [2021:09:16-12:10:38]
login-id: 21p1052@christjuniorcollege.edu.in
Ms-Teams-Auto-Joiner-Bot
Timeout error
.ms-CommandBar-secondaryCommand > div > button[class*='__topBarContent']
Time: [2021:09:16-12:10:44]
login-id: 21p1052@christjuniorcollege.edu.in
Ms-Teams-Auto-Joiner-Bot
No Teams found
is MS Teams in list mode? (switch to mode 3 if you only want calendar meetings)
Time: [2021:09:16-12:10:46]
login-id: 21p1052@christjuniorcollege.edu.in
Ms-Teams-Auto-Joiner-Bot
Browser closed
Thank you!
Time: [2021:09:16-12:10:49]
login-id: 21p1052@christjuniorcollege.edu.in

[config.json.example.txt](https://github.com/TobiasPankner/Teams-Auto-Joiner/files/7176011/config.json.example.txt)

**Comment by TobiasPankner** [comment]
Did you switch to list mode like it says?

**Comment by hanselsaji** [comment]
> Did you switch to list mode like it says?

Nope!
Just kept 1
for both channel and calendar.

**Comment by TobiasPankner** [comment]
You have to switch to list mode. Not in the config but in MS teams itself.

**Comment by hanselsaji** [comment]
> You have to switch to list mode. Not in the config but in MS teams itself.

Okay, I ave done it, and also switched the mode to 3....
Thank you !!
