### ISSUE TITLE
Heroku Support

### ISSUE THREAD

**Issue by LeibelRyan** [TobiasPankner/Teams-Auto-Joiner#149]
Please, add support for Heroku, We can host it on Heroku.

**Comment by TobiasPankner** [comment]
I have never worked with heroku but couldn't you just pull and execute it on a heroku server?  
What exactly do you mean by support for heroku?

**Comment by CoderZ90** [comment]
> I have never worked with heroku but couldn't you just pull and execute it on a heroku server? What exactly do you mean by support for heroku?

I think he wanted the bot to run on cloud. Cuz Heroku is hosting service

**Comment by TobiasPankner** [comment]
I know, but the bot should run fine on linux and headless so I don't see why it wouldn't work
