### ISSUE TITLE
I can't exit the meeting.

### ISSUE THREAD

**Issue by Abhranta** [TobiasPankner/Teams-Auto-Joiner#15]
I have windows 10 and I am using google chrome. I am able to join the meeting but I am unable to exit it. This is the error I am getting...

[01:44:29] Updating channels
Joined meeting: Bot test > General
Traceback (most recent call last):
  File ".\meeting_joiner.py", line 424, in <module>
    main()
  File ".\meeting_joiner.py", line 417, in main
    team.update_elem()
  File ".\meeting_joiner.py", line 162, in update_elem
    f"ul>li.team[role='treeitem']>div[data-tid='team-{self.name}-li']")
  File "D:\Users\Abhrant\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector    
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "D:\Users\Abhrant\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "D:\Users\Abhrant\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Users\Abhrant\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=84.0.4147.135)

**Comment by TobiasPankner** [comment]
Do you want to exit it manually or does the bot do it?  
If the bot does it, when exactly does the error occur?

**Comment by Abhranta** [comment]
The bot does it. The error occurs when I am the last one in the meeting.

**Comment by TobiasPankner** [comment]
What is the name of the team and channel where the bit crashes?  
There may be sone invalid characters in the names.

**Comment by Abhranta** [comment]
The name of the team is Bot test

**Comment by TobiasPankner** [comment]
Okay, that is a really weird error. What browser are you using?

**Comment by Abhranta** [comment]
Google Chrome

**Comment by TobiasPankner** [comment]
Can you please try renaming the Team from "Bot test" to something with no whitespace in it (eg BotTest). An then run it again

**Comment by Abhranta** [comment]
😅most of my classes have white spaces in the names..

**Comment by TobiasPankner** [comment]
Yeah, it's not a solution. I'm just trying to figure out what causes the bug so I can fix it. Right now I can't reproduce the error, therefore I can't fix it

**Comment by Abhranta** [comment]
Yep I will do that tomorrow.. it's 3am here now .. thanks for the help ! 🙂

**Comment by TobiasPankner** [comment]
Sure thing, sorry for asking so much

**Comment by TobiasPankner** [comment]
With commit 2b6aa0b this is hopefully fixed. Please pull the new version and try again.
