### ISSUE TITLE
The bot trying to join last meeting

### ISSUE THREAD

**Issue by thepronightly** [TobiasPankner/Teams-Auto-Joiner#150]
There are many afk people after meeting ends.
And the last meeting still joinable for this reason. What is the solution for this?
I did not understand well. Is pause_search option for this or not :/.
I'm not good at English. Sorry for my typo.

**Comment by TobiasPankner** [comment]
The bot should never join a meeting twice. If it does, that is a bug. 
Please comment the console log and config file (without email/pw !).

**Comment by TobiasPankner** [comment]
And pause_search is so the bot doesn't search for meetings while in one.

**Comment by thepronightly** [comment]
Okay it was my bad. The bots working great with no issues. Can you think about "closebot_at_time": like option. Thank you.
