### ISSUE TITLE
How to use opera GX instead of google chrome

### ISSUE THREAD

**Issue by GhostGamr** [TobiasPankner/Teams-Auto-Joiner#162]
hello,
can u pls help by telling me how to use opera gx instead of google chrome

**Comment by TobiasPankner** [comment]
This is not suppprted by default. However, you can change it manually.  
Here is some documentation on how to do it. 
https://pypi.org/project/webdriver-manager/

**Comment by TobiasPankner** [comment]
You have to change the code around line 180 in auto_joiner.py

**Comment by GhostGamr** [comment]
ok thnx
