### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hanselsaji** [TobiasPankner/Teams-Auto-Joiner#163]
C:\Users\soulh\Downloads\Telegram Desktop\Teams-Auto-Joiner-master\Teams-Auto-Joiner>python auto_joiner.py
Traceback (most recent call last):
  File "C:\Users\soulh\Downloads\Telegram Desktop\Teams-Auto-Joiner-master\Teams-Auto-Joiner\auto_joiner.py", line 8, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

C:\Users\soulh\Downloads\Telegram Desktop\Teams-Auto-Joiner-master\Teams-Auto-Joiner>

**Comment by TobiasPankner** [comment]
Install the dependencies, like described in the readme

**Comment by hanselsaji** [comment]
Done

C:\Users\soulh\Downloads\Telegram Desktop\Teams-Auto-Joiner-master\Teams-Auto-Joiner\Teams-Auto-Joiner>python auto_joiner.py
Traceback (most recent call last):
  File "C:\Users\soulh\Downloads\Telegram Desktop\Teams-Auto-Joiner-master\Teams-Auto-Joiner\Teams-Auto-Joiner\auto_joiner.py", line 14, in <module>
    from webdriver_manager.chrome import ChromeDriverManager
ModuleNotFoundError: No module named 'webdriver_manager'

C:\Users\soulh\Downloads\Telegram Desktop\Teams-Auto-Joiner-master\Teams-Auto-Joiner\Teams-Auto-Joiner>

**Comment by TobiasPankner** [comment]
Come on, please just read the readme and do the steps as described. You need to install all dependencies.  
Closing this because this is no problem with the bot.

**Comment by hanselsaji** [comment]
![photo_2022-01-06_19-28-43](https://user-images.githubusercontent.com/63719604/148394033-138036e8-3747-45f9-a7ce-155f0a9d7868.jpg)
![photo_2022-01-06_19-28-53](https://user-images.githubusercontent.com/63719604/148394040-563aeb4b-2526-4d0e-8951-cdbea3b60c6a.jpg)

**Comment by TobiasPankner** [comment]
Apprently the file you are trying to run does't exist. Have you watched the video that is linked in the readme?
