### ISSUE TITLE
Compatability with cron?

### ISSUE THREAD

**Issue by XEVMERSHALL** [TobiasPankner/Teams-Auto-Joiner#17]
**Is your feature request related to a problem? Please describe.**
I've tried running the script using cron, but it doesn't seem to work with it even if the full details of the python location + script are provided.

**Describe the solution you'd like**
To be able to schedule a cron job to automatically execute the script

**Describe alternatives you've considered**
Maybe a feature within the program itself to start looking for meetings to join at certain user-specified times.

**Additional context**
I want to schedule the time periods when the script is active and seeking meetings to join.

**Comment by TobiasPankner** [comment]
It should be compatible with cron, you have to set the email/pw, start_automatically to true and headless also to true. 
Please try again with this config and also pipe the output into a file to see whats going wrong.

**Comment by TobiasPankner** [comment]
I also just added an option to input a time to start searching at (like your  alternative suggestion).

**Comment by XEVMERSHALL** [comment]
Was wondering why it wasn't working for me, but then I noticed the stuff about wrong config value for auto start.
Thanks and much appreciated!
