### ISSUE TITLE
script seems to not work when left overnight 

### ISSUE THREAD

**Issue by xiUnknown1** [TobiasPankner/Teams-Auto-Joiner#177]
**Describe the bug**
When leaving the cmd task open and leaving my computer running overnight, simply, nothing happens. (it just says Waiting until 2022-03-23 07:20:00 (25504s)
One interesting thing I found is the script loaded when I moved/focused on the cmd task. 

**Configuration file**
[config - Copy.txt](https://github.com/TobiasPankner/Teams-Auto-Joiner/files/8331095/config.-.Copy.txt)

**Desktop (please complete the following information):**
 - OS: [Windows 11 22557.1]
 - Browser [chrome]
 - Version [99.0.4844.8 ]

**Comment by TobiasPankner** [comment]
What exactly is the issue here? It's not starting when it's supposed to?

**Comment by xiUnknown1** [comment]
Yes, it does not start after the waiting time.

**Comment by TobiasPankner** [comment]
That could be some weird thing with windows power managment.  
You could try starting the script at the time (without the wait until config).  
I don't know exactly how to do this but [this](https://help.globalscape.com/help/archive/cuteftp8/Running_Scripts_from_the_Windows_Scheduled_Tasks_folder.htm#:~:text=The%20Windows%20Task%20Scheduler%20is,the%20NT%204%20AT%20Scheduler.&text=Click%20Start%20%3E%20Programs%20%3E%20Accessories%20%3E,The%20Scheduled%20Task%20Wizard%20appears.) link should get you started.

**Comment by xiUnknown1** [comment]
Thanks for dedicating your time to us, love your work.

**Comment by TobiasPankner** [comment]
> Thanks for dedicating your time to us, love your work. 

You're welcome!
