### ISSUE TITLE
Trouble installing/running code

### ISSUE THREAD

**Issue by xxgamerluna** [TobiasPankner/Teams-Auto-Joiner#182]
**Describe the bug**
I was setting up the code but when I got to the part where you install the requirements.txt in the cmd it doesn't work.

**To Reproduce**

1. clicks on the path bar
2. types CMD
3. (Cmd pops up and says C:\Teams-Auto-Joiner-master>)
4. copies and pastes ( pip install -r requirements.txt ) as the codes pages say to
5. gets error message - 'pip' is not recognized as an internal or external command,
operable program or batch file.

**Expected behavior**
I expected it to run the file as it did in the video so that I can run the code.

**Screenshots**
![image](https://user-images.githubusercontent.com/54170507/195705254-5ce65e4c-5452-4bf8-a1f9-3ee8224ea596.png)
![image](https://user-images.githubusercontent.com/54170507/195705304-251bc3b5-6fe7-4157-b947-c6e525c632bb.png)

**Configuration file**

 "run_at_time": "11:50",

  "meeting_mode": 3,
  "organisation_num" : -1,
  "random_delay": [30,30],
  "check_interval": 8,

  "join_message": "",

  "auto_leave_after_min": -1,
  "leave_if_last": true,
  "leave_threshold_number": -1,
  "leave_threshold_percentage": -1,
  "pause_search": true,

  "headless" : false,
  "mute_audio": false,
  "chrome_type": "google-chrome",

  "blacklist": [
    
  ],
}

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 21H2  Microsoft Windows [Version 10.0.19044.2006]

**Additional context**

**Comment by TobiasPankner** [comment]
You have to add pip to path. This can be done when installing python.  
Closing this issue because it has nothing to do with the code
