### ISSUE TITLE
It says, the "config.json" file is not found

### ISSUE THREAD

**Issue by 0-3-6-9** [TobiasPankner/Teams-Auto-Joiner#20]
here is the error log
![image](https://user-images.githubusercontent.com/70578650/91939907-3d316e80-ed14-11ea-93f5-363e600f43f2.png)
here is the file where i stored the json file
![image](https://user-images.githubusercontent.com/70578650/91940059-7ff34680-ed14-11ea-8e83-7a093535824e.png)

**Comment by TobiasPankner** [comment]
You probably have file extensions disabled. Please enabls them and check the name of the file again.

**Comment by 0-3-6-9** [comment]
Super!
got my bug debugged... Thanks for your support 
: )
