### ISSUE TITLE
Joining the meeting depending upon the meeting name using Regex

### ISSUE THREAD

**Issue by Divyam10** [TobiasPankner/Teams-Auto-Joiner#21]
So I want to join the meetings only of my batch, which depends on the name of the meeting itself, if there is a way to fetch the name and decide. Like in the picture below I have to join the meeting with batch A2. 

![Screenshot from 2020-09-04 14-20-40](https://user-images.githubusercontent.com/29382463/92221258-d7cbb200-eeba-11ea-90b5-03a78a9f7b96.png)

For normal lectures intended for everyone it works really good. Thank you for that!

**Comment by TobiasPankner** [comment]
Do these meetings show up in the normal team menu or in the calendar?

**Comment by Divyam10** [comment]
> Do these meetings show up in the normal team menu or in the calendar?

In the calendar only!

**Comment by Divyam10** [comment]
Maybe someway I can fetch the meeting name I will add the condition.

**Comment by TobiasPankner** [comment]
As it is, meetings from the calendar are not supported. This is because I don't have a calendar on my Teams account so I cannot implement it.  
If you know how to, you can add the feature yourself, I would be very grateful for that.

**Comment by Divyam10** [comment]
@TobiasPankner Is there a way to get the meeting name? I don't have much experience with Selenium but I will it for sure.

**Comment by TobiasPankner** [comment]
You have to look at the html of the page and then write a css selector to select the element that contains the name.

**Comment by TobiasPankner** [comment]
Calendar meetings are now fully supported but the regex feature is too specific and right now I'll not add it. Feel free to fork the repo and implement it in your own version.

**Comment by Divyam10** [comment]
Alright Thanks You!
