### ISSUE TITLE
Waiting for correct page... Nothing found, is Teams in list mode?

### ISSUE THREAD

**Issue by Arpitcool11123** [TobiasPankner/Teams-Auto-Joiner#22]
As soon as i enter the login id and password at the Microsoft login page. It takes me to the option of opening it with the app or on browser. At this stage when I click browser. This comes in the code Waiting for correct page...
Nothing found, is Teams in list mode?

**Comment by TobiasPankner** [comment]
What is on your screen at the time of the error message? It should be a list of all team names to the left with a chat to the right.

**Comment by Arpitcool11123** [comment]
> What is on your screen at the time of the error message? It should be a list of all team names to the left with a chat to the right.

I am attaching the screenshot of the screen when this error comes.
![Screenshot (11)](https://user-images.githubusercontent.com/70982371/92590969-b3a51200-f2ba-11ea-867a-9f30100b4eb0.png)

**Comment by TobiasPankner** [comment]
What happens if you click "use the web app" right after logging in?

**Comment by Arpitcool11123** [comment]
When i click on use web instead , microsoft teams starts but no changes ...it still says are you in list mode

**Comment by TobiasPankner** [comment]
You have to click before it shows that. You should have enough time

**Comment by Arpitcool11123** [comment]
No bro it isn't.... First the page shows up for remeber sign in, then this page shows up and to this point the error comes no matter how fast i try

**Comment by TobiasPankner** [comment]
Try putting in your email/pw in ths config file. I will look into your issue when I find the time

**Comment by Arpitcool11123** [comment]
Ok please do it will be a great help

**Comment by TobiasPankner** [comment]
I cannot reproduce your issue, how many Teams are you a member in and have you made sure that the view is "list" and not "grid"?

**Comment by Arpitcool11123** [comment]
I am only a member of one team... The the code stops on the choose web istead page. After that i have a option to chose grid or list view right.

**Comment by TobiasPankner** [comment]
Open teams in a browser and setup the list view, then rerun the program

**Comment by Arpitcool11123** [comment]
https://photos.app.goo.gl/5yRCjnqhmACHNZJx6

**Comment by Arpitcool11123** [comment]
Use this link...i have created a video for the error

**Comment by TobiasPankner** [comment]
Thanks, that is very helpful. The problem is definietly that teams is in grid mode. Please open teams in a browser and change this (or ignore the error and change it there). Teams will remember your setting and start in list mode next time

**Comment by Arpitcool11123** [comment]
Yo bro...... Nice.... Got it. Now it will join to every available meeting right

**Comment by TobiasPankner** [comment]
Yes, it will always join the newest meeting available. You should see "Updating channels" every few seconds in the terminal

**Comment by Arpitcool11123** [comment]
Ok thanks man...
