### ISSUE TITLE
Cant run script in current Edge browser

### ISSUE THREAD

**Issue by chrizzler9** [TobiasPankner/Teams-Auto-Joiner#24]
**Describe the bug**
Hi, when trying to run the script with the msedge variable, the script seems to fail to find a current webdriver: 
ValueError: There is no such driver by url http://chromedriver.storage.googleapis.com/LATEST_RELEASE_85.0.564
I am running edge V 85.0.564.51

please halp :-)

**Comment by TobiasPankner** [comment]
Got it! Fixed with commit 5c6e043

**Comment by TobiasPankner** [comment]
I also just fixed a small bug introduced with this, so please update again
