### ISSUE TITLE
Joining Teams meetings which are not part of a channel

### ISSUE THREAD

**Issue by chrizzler9** [TobiasPankner/Teams-Auto-Joiner#25]
Hi, got a lot of meetings which are not associated to any Teams channels. Any option to integrate joining meetings which are in the teams calendar but do not belong to a channel?

Thanks, great script, appreciated.

**Comment by chrizzler9** [comment]
Hi, just read the last features requests and comments in which you mentioned that this is currently not supported and not planned. Thanks anyway

**Comment by chrizzler9** [comment]
Hi Tobias, I could really use that feature for my professional work and love the existing script. Any way you would be willing to purchase a license for teams which includes calendars and implement that feature for a paypal donation? Unfortunatly I am to lazy to learn python and selenium. If yes, fee free to message me / chrizzl90@msn.com. Kind Regards

**Comment by TobiasPankner** [comment]
I'm already working on it, for now you can test out the version on the second branch. But keep in mind that this might not work perfectly.

**Comment by chrizzler9** [comment]
Awesome. Will be offline for 4 weeks now but happy to test and provide feedback afterwards if you find this helpful
