### ISSUE TITLE
can not join the meeting 

### ISSUE THREAD

**Issue by H4D53** [TobiasPankner/Teams-Auto-Joiner#26]
i used python 3.8.5 ( downloaded from python.org) and python 3.8 ( downloaded from Microsoft Store)
when it detected a meeting had started by organizer , it output some errors ,
here is the python 3.8 output :
`Traceback (most recent call last):
  File "C:\Users\hmcha\Desktop\Teams-Auto-Joiner-master\auto_joiner.py", line 442, in <module>
    main()
  File "C:\Users\hmcha\Desktop\Teams-Auto-Joiner-master\auto_joiner.py", line 417, in main
    if join_newest_meeting(teams):
  File "C:\Users\hmcha\Desktop\Teams-Auto-Joiner-master\auto_joiner.py", line 227, in join_newest_meeting
    join_btn.click()
  File "C:\Users\hmcha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\hmcha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\hmcha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\hmcha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button type="button" class="ts-sym ts-btn ts-btn-primary inset-border icons-call-jump-in ts-calling-join-button app-title-bar-button app-icons-fill-hover call-jump-in" ng-class="(ctrl.roundButton ?
                (ctrl.audioOnly ? 'icons-call-audio' : 'icons-call-video-filled') + ' inset-border inset-border-round ts-calling-join-button app-title-bar-button app-icons-fill-hover'
                : ctrl.joinButtonWithIcon ? 'icons-call-jump-in ts-calling-join-button app-title-bar-button app-icons-fill-hover call-jump-in'
                : ctrl.isBannerButton ? 'call-jump-in no-icons-call-jump-in ts-calling-banner-button' : 'call-jump-in no-icons-call-jump-in')" ng-click="ctrl.joinCall()" track-outcome="5" track-scenario="795" track-scenario-type="22" track-name="317" track-type="42" track-summary="Join an ongoing meetup from the channel ongoing meeting object" track-data="{callId: '0dfa7834-31b0-4f63-a3bc-b05ca9989d55', correlationId: '1ecdbfce-141c-4c63-98ac-347eed83377c'}" ng-disabled="ctrl.reallyDisabled" title="Join call with audio" data-tid="join-btn-0dfa7834-31b0-4f63-a3bc-b05ca9989d55">...</button> is not clickable at point (217, 478). Other element would receive the click: <span ng-if="!clc.filterString" class="truncate header-text" title="..." dir="auto">ITP3901-OSF-2021-S1-1A-khtong</span>
  (Session info: chrome=85.0.4183.102)`

and here is the python 3.8.5 output 
`Traceback (most recent call last):
  File "auto_joiner.py", line 442, in <module>
    main()
  File "auto_joiner.py", line 417, in main
    if join_newest_meeting(teams):
  File "auto_joiner.py", line 227, in join_newest_meeting
    join_btn.click()
  File "C:\Users\hmcha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\hmcha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\hmcha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\hmcha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button type="button" class="ts-sym ts-btn ts-btn-primary inset-border icons-call-jump-in ts-calling-join-button app-title-bar-button app-icons-fill-hover call-jump-in" ng-class="(ctrl.roundButton ?
                (ctrl.audioOnly ? 'icons-call-audio' : 'icons-call-video-filled') + ' inset-border inset-border-round ts-calling-join-button app-title-bar-button app-icons-fill-hover'
                : ctrl.joinButtonWithIcon ? 'icons-call-jump-in ts-calling-join-button app-title-bar-button app-icons-fill-hover call-jump-in'
                : ctrl.isBannerButton ? 'call-jump-in no-icons-call-jump-in ts-calling-banner-button' : 'call-jump-in no-icons-call-jump-in')" ng-click="ctrl.joinCall()" track-outcome="5" track-scenario="795" track-scenario-type="22" track-name="317" track-type="42" track-summary="Join an ongoing meetup from the channel ongoing meeting object" track-data="{callId: '0dfa7834-31b0-4f63-a3bc-b05ca9989d55', correlationId: '5d0588c4-a5ae-43f4-8ef5-7dd149fc9065'}" ng-disabled="ctrl.reallyDisabled" title="Join call with audio" data-tid="join-btn-0dfa7834-31b0-4f63-a3bc-b05ca9989d55">...</button> is not clickable at point (217, 478). Other element would receive the click: <span ng-if="!clc.filterString" class="truncate header-text" title="..." dir="auto">ITP3901-OSF-2021-S1-1A-khtong</span>
  (Session info: chrome=85.0.4183.102)`

**Comment by H4D53** [comment]
it seems like it can not click the join button, so i was trying to find the some related element on the website and found this:

<calling-join-button button-disabled="ctrl.disableJoinButton" call-info="ctrl.callInfo" join-context="channel" join-button-with-icon="true" title="ctrl.title"><button type="button" class="ts-sym ts-btn ts-btn-primary inset-border icons-call-jump-in ts-calling-join-button app-title-bar-button app-icons-fill-hover call-jump-in" ng-class="(ctrl.roundButton ?
                (ctrl.audioOnly ? 'icons-call-audio' : 'icons-call-video-filled') + ' inset-border inset-border-round ts-calling-join-button app-title-bar-button app-icons-fill-hover'
                : ctrl.joinButtonWithIcon ? 'icons-call-jump-in ts-calling-join-button app-title-bar-button app-icons-fill-hover call-jump-in'
                : ctrl.isBannerButton ? 'call-jump-in no-icons-call-jump-in ts-calling-banner-button' : 'call-jump-in no-icons-call-jump-in')" ng-click="ctrl.joinCall()" track-outcome="5" track-scenario="795" track-scenario-type="22" track-name="317" track-type="42" track-summary="Join an ongoing meetup from the channel ongoing meeting object" track-data="{callId: '0dfa7834-31b0-4f63-a3bc-b05ca9989d55', correlationId: '7806553b-b373-4856-942b-8bc0f5d61955'}" ng-disabled="ctrl.reallyDisabled" title="Join call with audio" data-tid="join-btn-0dfa7834-31b0-4f63-a3bc-b05ca9989d55"><span ng-if="!ctrl.roundButton" translate-once="calling_jumpIn" aria-label="Join">Join</span></button></calling-join-button>

even though i found these element and error ( as i think) , i do not know which function or code name to replace tho, since i just start learning python at 1st Sep 2020,  and also thanks for looking my issues

**Comment by H4D53** [comment]
it seems like it can not click the join button, so i was trying to find the some related element on the website and found this:

'<calling-join-button button-disabled="ctrl.disableJoinButton" call-info="ctrl.callInfo" join-context="channel" join-button-with-icon="true" title="ctrl.title"><button type="button" class="ts-sym ts-btn ts-btn-primary inset-border icons-call-jump-in ts-calling-join-button app-title-bar-button app-icons-fill-hover call-jump-in" ng-class="(ctrl.roundButton ? (ctrl.audioOnly ? 'icons-call-audio' : 'icons-call-video-filled') + ' inset-border inset-border-round ts-calling-join-button app-title-bar-button app-icons-fill-hover' : ctrl.joinButtonWithIcon ? 'icons-call-jump-in ts-calling-join-button app-title-bar-button app-icons-fill-hover call-jump-in' : ctrl.isBannerButton ? 'call-jump-in no-icons-call-jump-in ts-calling-banner-button' : 'call-jump-in no-icons-call-jump-in')" ng-click="ctrl.joinCall()" track-outcome="5" track-scenario="795" track-scenario-type="22" track-name="317" track-type="42" track-summary="Join an ongoing meetup from the channel ongoing meeting object" track-data="{callId: '0dfa7834-31b0-4f63-a3bc-xxxxxxxx', correlationId: '7806553b-b373-4856-942b-xxxxxxxx'}" ng-disabled="ctrl.reallyDisabled" title="Join call with audio" data-tid="join-btn-0dfa7834-31b0-4f63-a3bc-xxxxxxxxxx"><span ng-if="!ctrl.roundButton" translate-once="calling_jumpIn" aria-label="Join">Join</span></button></calling-join-button>'

thanks for looking my issues

**Comment by TobiasPankner** [comment]
You are right, something is covering up the button that it would click.  
What is shown on screen when the error occurs (a screenshot would be great)?

**Comment by H4D53** [comment]
![image](https://user-images.githubusercontent.com/47973426/93432537-4287df00-f8f8-11ea-870b-9ca905dda51d.png)
same error code as i have sent

**Comment by H4D53** [comment]
i did not change the chrome window size btw

**Comment by H4D53** [comment]
and i tried not to move them , let them stayed where they appear , still show the same error code at the command prompt.

**Comment by TobiasPankner** [comment]
It seems like the side menu (where the team names are) is covering up the join button. Try making the window wider

**Comment by H4D53** [comment]
oh no, it just the window size problem omg, thank you so much sir , but is it possible to make the window wider automatically? like change some code in the auto_joiner.py?

**Comment by H4D53** [comment]
i have changed the code line to browser.set_window_size(1920, window_size['width']) , and now it works perfectly, thank you for your helping and your extremely useful tool

**Comment by TobiasPankner** [comment]
You're welcome, glad you like it!  
In the code I set it to the width that worked for most screens.  
At what minmum width did it work so I can change it in the code? You can check the width with the chrome dev tools
