### ISSUE TITLE
Getting Webdriver.Chrome Syuntax error

### ISSUE THREAD

**Issue by h0ay** [TobiasPankner/Teams-Auto-Joiner#28]
I am using this script on my pi -raspbian 

I am getting this error 

`File "auto_joiner.py", line 18
    browser: webdriver.Chrome = None
           ^
SyntaxError: invalid syntax`

My current config 

{
  "email": "using my email",
  "password": "usingmypassword",

  "run_at_time": "",

  "start_automatically": false,
  "organisation_num" : 1,
  "random_delay": false,
  "check_interval": 5,

  "auto_leave_after_min": -1,
  "leave_if_last": true,

  "headless" : false,
  "mute_audio": false,
  "chrome_type": "google-chromium",

  "blacklist": [
    {
      "team_name": "Example Team 1",
      "channel_names": [
        "First Channel to blacklist in this team",
        "Second Channel to blacklist"
      ]
    },
     {
      "team_name": "Blacklist whole team",
      "channel_names": [
      ]
    }
  ]
}

**Comment by TobiasPankner** [comment]
What python version are you using? It needs to be >3.6

**Comment by h0ay** [comment]
2.7.13

**Comment by h0ay** [comment]
and 3.5.3

**Comment by TobiasPankner** [comment]
Well there you have it, upgrade to python 3.6 or newer

**Comment by h0ay** [comment]
Okay thanks

**Comment by h0ay** [comment]
Will sudo apt-get update and upgrade fix it ? or what's the command ?

**Comment by TobiasPankner** [comment]
Heres what I found: http://www.knight-of-pi.org/installing-python3-6-on-a-raspberry-pi/

**Comment by h0ay** [comment]
How can i fix this ?
'Traceback (most recent call last):
  File "auto_joiner.py", line 8, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium' '

**Comment by TobiasPankner** [comment]
Just read the readme. Install the dependencies

**Comment by h0ay** [comment]
```
pi@raspberrypi:~/Teams-Auto-Joiner $   pip install -r requirements.txt

Collecting webdriver_manager==3.2.0 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement webdriver_manager==3.2.0 (from -r requirements.txt (line 1)) (from versions: 1.0, 1.1, 1.2, 1.3, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5, 1.5.1, 1.6, 1.6.2, 1.7, 1.8, 1.8.2, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.4.0)
No matching distribution found for webdriver_manager==3.2.0 (from -r requirements.txt (line 1))

```

**Comment by h0ay** [comment]
I used pip3 also but gives me some ssl problem

so installed webdriver and selenium manually but still it shows selenium model not available

**Comment by TobiasPankner** [comment]
pip install --upgrade pip

**Comment by TobiasPankner** [comment]
I don't know, but this has nothing to do with the program. It's a python/pip problem. Look the issue up and try those solutions

**Comment by h0ay** [comment]
```
pi@raspberrypi:~/Teams-Auto-Joiner $ python3 auto_joiner.py
Traceback (most recent call last):
  File "auto_joiner.py", line 14, in <module>
    from webdriver_manager.chrome import ChromeDriverManager
ModuleNotFoundError: No module named 'webdriver_manager'
```

I already have webdriver_manager installed 

Using it with chromium
