### ISSUE TITLE
program stucks

### ISSUE THREAD

**Issue by H4D53** [TobiasPankner/Teams-Auto-Joiner#30]
not working after resize the window height
the browser stuck in Assignment page , whatever the mode is 1 or 3 , just stay at the Assignment page then error the close itself
 after like 5 mins , it showed waiting for correct page ... timeout , and closed chrome and itself 
`
C:\Users\xxx\Desktop\Teams-Auto-Joiner-master>python auto_joiner.py

[WDM] - Current google-chrome version is 85.0.4183
[WDM] - Get LATEST driver version for 85.0.4183
[WDM] - Driver [C:\Users\hmcha\.wdm\drivers\chromedriver\win32\85.0.4183.87\chromedriver.exe] found in cache

DevTools listening on ws://127.0.0.1:10491/devtools/browser/f7edd452-58da-4ec8-afdc-66030d5b0425
Resized window
Waiting for correct page...Timeout waiting for element: div[data-tid='team-channel-list']

C:\Users\xxxDesktop\Teams-Auto-Joiner-master>pause
Press any key to continue . . .
`

**Comment by H4D53** [comment]
content of config file
`  
{
  "email": "not null",
  "password": "not null",

  "run_at_time": "",

  "meeting_mode": 1,
  "organisation_num" : 1,
  "random_delay": false,
  "check_interval": 60,

  "auto_leave_after_min": -1,
  "leave_if_last": true,

  "headless" : false,
  "mute_audio": true,
  "chrome_type": "google-chrome",

  "blacklist": [
    {
      "team_name": "Example Team 1",
      "channel_names": [
        "First Channel to blacklist in this team",
        "Second Channel to blacklist"
      ]
    },
     {
      "team_name": "Blacklist whole team",
      "channel_names": [
      ]
    }
  ]
}`

**Comment by TobiasPankner** [comment]
What is shown in the browser when the timeout happens? Did you try clicking on the teams tab yourself?

**Comment by H4D53** [comment]
it can be fixed by click the Teams on the left side manually
also when scanning at calendar , it show timeout waiting for element; .ts-calling-thread-header
but it will back to Channel list automatically so its just fine if it just check the channel list without calendar

**Comment by TobiasPankner** [comment]
Got it, thanks for the feedback. I'll add the automatic switching to the Teams tab as soon as possible.

**Comment by H4D53** [comment]
but if i open teams page myself , the default page is channel list 
but if program opens the teams page , the default page is Assignment page

**Comment by H4D53** [comment]
> it can be fixed by click the Teams on the left side manually
> also when scanning at calendar , it show timeout waiting for element; .ts-calling-thread-header
> but it will back to Channel list automatically so its just fine if it just check the channel list without calendar

or maybe the next coming up meeting is 1hours 30 mins later so there is no button to join and makes a log of timeout for element , i will try when the meeting is close

**Comment by H4D53** [comment]
> it can be fixed by click the Teams on the left side manually
> also when scanning at calendar , it show timeout waiting for element; .ts-calling-thread-header
> but it will back to Channel list automatically so its just fine if it just check the channel list without calendar

update for this.
the log of ('Timeout waiting for element: .ts-calling-thread-header') seems appear after scan the channel list and before jump to calendar

**Comment by TobiasPankner** [comment]
Are there any active meetings in the channels?

**Comment by TobiasPankner** [comment]
With the newest version your first issue (the "waiting for correct page" one) is fixed

**Comment by H4D53** [comment]
the next coming up meeting at 8:30AM Hong Kong Standard Time GMT+8

**Comment by TobiasPankner** [comment]
Okay, can please post the console log?

**Comment by H4D53** [comment]
`[WDM] - Current google-chrome version is 85.0.4183
[WDM] - Get LATEST driver version for 85.0.4183
[WDM] - Driver [C:\Users\xxx\.wdm\drivers\chromedriver\win32\85.0.4183.87\chromedriver.exe] found in cache

DevTools listening on ws://127.0.0.1:14159/devtools/browser/e56d42e4-b3f9-48a3-b2d3-5b044ca6e180
Resized window
Found page, do not click anything on the webpage from now on.

('censored because my classes and teachers names are here')

[07:02:36] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:03:52] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:05:08] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:06:25] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:07:42] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:08:58] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:10:14] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:11:31] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:12:47] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:14:03] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:15:21] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:16:37] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:17:54] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:19:11] Looking for new meetings`

**Comment by H4D53** [comment]
`[WDM] - Current google-chrome version is 85.0.4183
[WDM] - Get LATEST driver version for 85.0.4183
[WDM] - Driver [C:\Users\xxx.wdm\drivers\chromedriver\win32\85.0.4183.87\chromedriver.exe] found in cache

DevTools listening on ws://127.0.0.1:14159/devtools/browser/e56d42e4-b3f9-48a3-b2d3-5b044ca6e180
Resized window
Found page, do not click anything on the webpage from now on.

('List of the meetings')

[07:02:36] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:03:52] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:05:08] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:06:25] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:07:42] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:08:58] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:10:14] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:11:31] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:12:47] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:14:03] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:15:21] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:16:37] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:17:54] Looking for new meetings
Timeout waiting for element: .ts-calling-thread-header

[07:19:11] Looking for new meetings`

**Comment by TobiasPankner** [comment]
Thanks, is there a "[MEETING]" next to any channel name in the list of teams/channels?

**Comment by H4D53** [comment]
nope

**Comment by H4D53** [comment]
names are made by lecture code , my class and the teacher names

**Comment by TobiasPankner** [comment]
Okay, try again with the newest version please. If it's still not changed ignore the timeout error and see if it still works as expected. I am closing this issue now, if there are other problems please open another one. Thanks

**Comment by TobiasPankner** [comment]
Sorry I messed something up, next commit should be working

**Comment by TobiasPankner** [comment]
Both should be fixed with commit 1890917
