### ISSUE TITLE
python auto_joiner.py not working

### ISSUE THREAD

**Issue by DumbBoy2** [TobiasPankner/Teams-Auto-Joiner#34]
**Describe the bug**
I followed all the steps up until typing "python auto_joiner.py". Then the error came. I'm know nearly nothing of python and programming. So could you help a newbie like me? 

Here is the errror:
https://imgur.com/a/ztI1Tro

It just blocks here and does nothing. 

**Configuration file**
{
  "email": "Removed for explanation purposes",
  "password": "Removed for explanation purposes",

  "run_at_time": "",

  "meeting_mode": 1,
  "organisation_num" : 1,
  "random_delay": true,
  "check_interval": 10,

  "auto_leave_after_min": 110,
  "leave_if_last": true,

  "headless" : false,
  "mute_audio": false,
  "chrome_type": "google-chrome",

  "blacklist": [
    {
      "team_name": "Lingua giapponese 1 (dalla Chiesa)",
      "channel_names": [
        "Esercitazioni di lingua giapponese 1 L-Z(Yamasaki)"      ]
    },
     {
      "team_name": "Lingua Inglese 1 MED 2020-21",
      "channel_names": [
      ]
    }
  ]
},      {
      "team_name": "Lingua Inglese II MED 2020-21",
      "channel_names": [
      ]
    }
  ]
}, {
      "team_name": "CULTURA INGLESE I MED. - LEZIONI - AA 2020/21 -",
      "channel_names": [
        "RANGE A-D. Proff. PASOLINI-VALLORANI",
 "RANGE N-Z. Prof MONEGATO"      ]
    }, {
      "team_name": "Lingua Inglese 1 MED 2020-2021 Language Skills B (Grammar Part 2 & Vocabulary)",
      "channel_names": [
        "Language Skills B Group 1", "Language Skills B Group 3", "Language Skills B Group 4", "Language Skills B Group 5", "Language Skills B Group 6", "Language Skills B Group 7", "Language Skills B Group 8", "Language Skills B Group 9", "Language Skills B Group 10"      ]
    }, {
      "team_name": "Lingua Inglese 1 MED 2020-2021 Language Skills A (Grammar Part 1)",
      "channel_names": [
        "Language Skills A Group 1", "Language Skills A Group 3", "Language Skills A Group 4", "Language Skills A Group 5", "Language Skills A Group 2", "Language Skills A Group 7", "Language Skills A Group 8", "Language Skills A Group 9", "Language Skills A Group 10"      ]
    } ] }

**Desktop:**
 - OS: windows 8.1
 - Browser chrome

**Comment by TobiasPankner** [comment]
There is an issue with the formattig of your config.json file.  
This is probably due to a missing comma or something similar.  
You can copy the content of you json file into a formatter like this one https://jsonformatter.curiousconcept.com/ this way you can better find the problem.

**Comment by DumbBoy2** [comment]
Thank you very much now it works! It was a problem with a bunch of random ] that i wasn't able to see in the config file... 

Now he worked fine but joined a meetingthat was blacklisted because it was also listed in the calendar. I've now changed that option to 2  so that it will pick up only meetings from the channels, and avoid the blacklisted one. I don't think i'll have other problems but I need to wait and see. 

In the meantime, just for curiosity, is denying events from the calendar or even hiding channels an effective alternative way to blacklist?

**Comment by TobiasPankner** [comment]
Hiding channels to blacklist should work. About denying events I'm not sure but you can try
