### ISSUE TITLE
Whitelist instead of blacklist

### ISSUE THREAD

**Issue by casualinformee** [TobiasPankner/Teams-Auto-Joiner#37]
**Is your feature request related to a problem? Please describe.**
I find that putting lots of teams in the `config.json` is a bit annoying. I'd rather put one or two team names in a whitelist, and have the script only search through those.

**Describe the solution you'd like**
I think having a whitelist for searching through teams would be better than using a blacklist.
If a user is only participating in one or a few teams, but has access to more than that, a whitelist would make it easier and faster to set the `config.json` to only look for meetings in the teams the user participates in.

**Describe alternatives you've considered**
It's possible to implement both a blacklist and a whitelist, and let the user choose which one to use, but it might be too clunky and unnecessarily complicated.

**Additional context**
Whitelisting vs blacklisting depends on each user case, but I think most users would prefer using a whitelist to choose which Teams the script should search in for meetings.

**Comment by TobiasPankner** [comment]
In my experience most people only have access to the teams they would actually like to join. And as you mentioned, both a whitelist and a blacklist would be too confusing.  
If it is an option for you, you can also hide Teams in MS Teams directly and "blacklist" them that way.

**Comment by casualinformee** [comment]
Okay, thank you for the tip! I have hidden some team names in Microsoft Teams, and they're no longer seen by the script. Closing this issue.
