### ISSUE TITLE
leave if participants in a meeting are lower than a threshold 

### ISSUE THREAD

**Issue by Radd-max** [TobiasPankner/Teams-Auto-Joiner#42]
sometimes in a meeting there are kids afk and stay in the meeting for a long time after its over , so could you please add an option where it will auto leave if there are less than 'x'  participants( or 'z' percent of total participants )remaining  after ' y' time has passed in a meeting

**Comment by Anirudh171202** [comment]
yes please

**Comment by jevonmao** [comment]
Sounds easy to implement. I might start working on this, I just want to make sure that this project is still active and @TobiasPankner is still approving pull requests. Thank you

**Comment by jevonmao** [comment]
Nice, thank you
