### ISSUE TITLE
I wish I could actually watch the meeting

### ISSUE THREAD

**Issue by LuigiCapovilla** [TobiasPankner/Teams-Auto-Joiner#43]
I just cant watch my meetings because the window is very small. I tried to change the window width and height, but the program just stopped working, and when I try to manually expand it, the meeting get window-sized again after the time set in the config.json

I wish I could watch the full meeting in full screen without having to maximize it every time

**Comment by TobiasPankner** [comment]
I know that some people want this but it would be quite complicated to implement. Besides, I don't really see the usage because if you are in front of your PC anyway you can manually attend the meeting.

**Comment by LuigiCapovilla** [comment]
I´d like to have this option because I use Teams for school, so when I'm not in a meeting, I'm doing schoolwork (Not paying attention to the clock), which already caused me to lose many meetings

**Comment by TobiasPankner** [comment]
Is the meeting window small or the whole chrome page?

**Comment by LuigiCapovilla** [comment]
![image](https://user-images.githubusercontent.com/73537099/97329448-ccab5780-1855-11eb-974d-a40b40efa3dd.png)

**Comment by LuigiCapovilla** [comment]
For now I just increased the searching time to 10 minutes, now I just have to maximize the window 5-6 times per meeting

**Comment by ntaraujo** [comment]
I think u can set "mute_audio" or even "headless"
To watch the meeting you can attend in other page/app

I don't know if other people can see your dual connection, but I always do this with my phone and pc (and some teachers too) for reasons such as the lack of a webcam

**Comment by Jotterloo** [comment]
Great to see the option to join calendar meetings!
Now facing the same issue as Luigi, the minimized meeting screen.
My intention was to use this for a unattended meeting Room account/device with a central placed screen.

Could it be an option to disable the reloading when a meeting is active?

**Comment by TobiasPankner** [comment]
So you want the bot to stop after the first meeting is joined?

**Comment by Jotterloo** [comment]
yes, maybe sleep the timer (process) or something like that.
And restart when the current active meeting is ended.

**Comment by TobiasPankner** [comment]
What do you mean by the meeting is ended? As I tested it will not be ended until everyone leaves.

**Comment by Jotterloo** [comment]
Well, when the meeting is ended, everybody leaves and the bot end the meeting (according config).
Then the check_interval should start again to look for the next meeting.

**Comment by TobiasPankner** [comment]
This feature is added with commit ede2a99
