### ISSUE TITLE
Multiple active meetings

### ISSUE THREAD

**Issue by TheMedicalGuy** [TobiasPankner/Teams-Auto-Joiner#47]
**Is your feature request related to a problem? Please describe.**
Using Teams to automate joining my university classes. One problem which arises is if there are two simultaneous meetings, the bot usually joins the earlier meeting, instead of the later one.

**Describe the solution you'd like**
Well, it would be great if in the config.json file we could pass an argument as to which meeting we can join.

**Describe alternatives you've considered**
I have a totally rudimentary idea of python, but would it be possible to segregate the meetings by the time created? Or the current running time? Or maybe the number of participants?
Then, would it be possible to join the meeting with the more recent creation time, or the lesser total running time, or the more number of participants?

**Comment by TobiasPankner** [comment]
This is a bug, it should always join the newer meeting. Please send me the console log and/or a video

**Comment by TheMedicalGuy** [comment]
The console log is as follows

C:\Users\XXX\Desktop\Teams-Auto-Joiner-master\Teams-Auto-Joiner-master>python auto_joiner.py

[WDM] - Cache is valid for [04/11/2020]
[WDM] - Looking for [chromedriver 86.0.4240.22 win32] driver in cache
[WDM] - Driver found in cache [C:\Users\XXX\.wdm\drivers\chromedriver\86.0.4240.22\win32\chromedriver.exe]

DevTools listening on ws://127.0.0.1:65390/devtools/browser/75b05875-838e-4e51-b7a3-ddc5814c6d84
Resized window width
Resized window height
Found page, do not click anything on the webpage from now on.
Timeout waiting for element: button.app-bar-link > ng-include > svg.icons-calendar
Timeout waiting for element: .ms-CommandBar-secondaryCommand > div > button[class*='__topBarContent']

XXXXXXXX
        General [MEETING]

[13:02:42] Looking for new meetings
Timeout waiting for element: button.app-bar-link > ng-include > svg.icons-calendar
Timeout waiting for element: div[class*='__cardHolder']
Found meetings:
        XXXXXXXX -> General 1604292591 [Channel]
        XXXXXXXX -> General 1604292547 [Channel]
Video off
Audio off
Joined meeting: XXXXXXXX -> General

**Comment by TobiasPankner** [comment]
What do you mean by "made active"?

**Comment by TheMedicalGuy** [comment]
The meetings are usually scheduled days before, to occur at a specific time. But someone needs to actually start the meeting, and that can happen before the scheduled time.
That's what I meant by "made active".

**Comment by TobiasPankner** [comment]
Okay, can you send me a screenshot of such a scheduled meeting.

**Comment by TheMedicalGuy** [comment]
![image](https://user-images.githubusercontent.com/73929405/98205152-9b214300-1f5d-11eb-9b07-2f6034eebf92.png)
I think the issue is being the script joins the later **scheduled** meeting, instead of the more recently created, i.e. started/made active, meeting.

**Comment by TobiasPankner** [comment]
Okay, so this meeting shows up in the calendar? If that is so, this is intended behaviour as in the calendar it looks at the start time of the meeting (here 1PM) and joins the latest active one.

**Comment by TheMedicalGuy** [comment]
Ok, then it's fine. It's just something I'll work around.
