### ISSUE TITLE
Add config option: start site muted

### ISSUE THREAD

**Issue by BRO3886** [TobiasPankner/Teams-Auto-Joiner#5]
I just want to join the online class for attendance with chrome muted 

```python
chrome_options.add_argument("--mute-audio")
```

add this to code and a config option for the same

**Comment by TobiasPankner** [comment]
What do you mean by "start site muted"?

**Comment by BRO3886** [comment]
I don't want to hear what's going on, instead focus on other stuff while the online class is going on. So, as a config (optional) setting I was suggesting maybe you could add an option where people can start auto joiner muted, so chrome starts muted and they can continue doing what they were doing while the online class goes on

**Comment by TobiasPankner** [comment]
Done with commit 91430bf
