### ISSUE TITLE
Stop searching for meetings

### ISSUE THREAD

**Issue by emmismtv** [TobiasPankner/Teams-Auto-Joiner#53]
Hey! I'm having online classes, and there is a problem that when the meetings has started it appears in a minimized window, and the bot keeps searching for classes. 

I think it would be pretty nice, if the bot could stop searching when the meeting has started and then run again when the meeting ends.

**Comment by TobiasPankner** [comment]
What do you define as "ends", when you are the last person in the meeting?

**Comment by TobiasPankner** [comment]
This feature is added with commit ede2a99
