### ISSUE TITLE
Program keeps searching for meetings even after joining and entering one.

### ISSUE THREAD

**Issue by PierreP15** [TobiasPankner/Teams-Auto-Joiner#59]
This program is near perfect and works beautifully except for the fact that it keeps searching for new meetings in the background despite having found and joined a current meeting. This causes issues like leaving the meeting that it's currently in, joining other random meetings etc. Is there a way you know that can fix this?

**Comment by TobiasPankner** [comment]
This feature is added with commit ede2a99
