### ISSUE TITLE
Staying in the disclosed meetings 

### ISSUE THREAD

**Issue by notrealgosu** [TobiasPankner/Teams-Auto-Joiner#6]
Hey, bot currently stays in the meeting even though no one left in the current meeting, can you add an option:

if organizer leaves:
  leave meeting
  blacklist meeting

or 

if you are the only user:
  leave meeting
  blacklist meeting

in order not to keep joining the same open meetings, blacklist that specific meeting with the url or an ID (if possible)

**Comment by TobiasPankner** [comment]
Very good suggestion. I'll try to implement it as soon as possible.

**Comment by TobiasPankner** [comment]
Added with commit 769e618. Thanks for the suggestion.
