### ISSUE TITLE
It doesn't see the Teams

### ISSUE THREAD

**Issue by Tarrare-the-Behemoth** [TobiasPankner/Teams-Auto-Joiner#69]
It works up until it is on the page displaying the Teams I am in. 
That is when it exits before checking them. I have tried setting meeting_mode to 1, 2, and 3 although my meetings are mostly channel meetings.

The output:
[WDM] - Current google-chrome version is 87.0.4280
[WDM] - Get LATEST driver version for 87.0.4280
[WDM] - Driver [C:\87.0.4280.88\chromedriver.exe] found in cache

Resized window width
Resized window height
Found page, do not click anything on the webpage from now on.
Not Teams found, is MS Teams in list mode? (switch to mode 3 if you only want calendar meetings)

**Comment by TobiasPankner** [comment]
Can you submit a video or screenshot of the chrome window?

**Comment by zufcenak** [comment]
I had this issue too, do you have MS Teams set to view in list? It is very important for the script to work

**Comment by Tarrare-the-Behemoth** [comment]
It works now, thanks!
