### ISSUE TITLE
Crashes on meeting hangup

### ISSUE THREAD

**Issue by avi-01** [TobiasPankner/Teams-Auto-Joiner#70]
It produces an error when it tries to hangup a meeting.

selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button id="hangup-button" ng-if="handler.visible" ng-class="handler.configuration.cssClasses" ng-click="handler.executeAction($event)" ng-disabled="handler.disabled" data-tid="call-hangup" track-name="594" track-summary="Hang up in unified bar" track-outcome="5" track-scenario="672" track-scenario-type="30" track-type="15" track-data="{&quot;ubarContext&quot;:&quot;call_screen&quot;,&quot;callId&quot;:&quot;c599c208-2386-459f-bce4-47fc16245c2e&quot;,&quot;participantId&quot;:&quot;9b27df54-ce30-4df4-802b-dbc2a7b56289&quot;,&quot;callType&quot;:&quot;VOIP or Interop&quot;}" track-async-data="handler.tracker.trackAsyncData()" aria-label="Hang up" calling-screen-focus="hang-up-button" ng-focus="handler.showTooltip($event, true)" ng-blur="handler.hideTooltip($event)" class="ts-push-button-action ts-sym togglable inset-border ts-hangup ts-push-button-animation">...</button> is not clickable at point (1042, 638). Other element would receive the click: <div class="ts-calling-participant-stream flex-fill inset-border item item0 is-muted connected allowImmersive" ng-focus="ctrl.onFocus()" ng-blur="ctrl.onBlur()" ng-mouseup="ctrl.onClick($event)" ng-keydown="ctrl.onKeyDown($event)" ts-right-click="ctrl.showContextMenu($event)" acc-role-dom="listgrid-item-dom" aria-haspopup="menu" grid-position-x="0" grid-position-y="0" aria-label="" role="listitem" calling-screen-focus="calling-participant" tabindex="-1" zoomable-stream="" ng-class="{
    'is-screen-share': ctrl.streamModel.isScreenShare,
    'is-screen-share-from-chat': ctrl.isScreenshareFromChat(),
    'has-screen-share-indicator': ctrl.showScreenShareIndicator,
    'is-muted': ctrl.isMuted(),
    'is-hand-raised': ctrl.isHandRaised(),
    'is-holographic': ctrl.isHolographic(),
    'vdi-dynamic-occlusion': ctrl.isVDIOcclusion,
     speaking: ctrl.isSpeaking(),
     hasvideo: ctrl.isVideoRendering,
     isLive: ctrl.isUserBroadcasting,
     leaving: ctrl.isLeaving(),
     connecting: ctrl.isConnecting(),
     connected: ctrl.isConnected(),
     isReconciled: ctrl.isReconciledPstnParticipant(),
     isSmall: ctrl.isSmallSize,
     allowImmersive: !ctrl.isPstn
  }" acc-listgrid-item="">...</div>
  (Session info: chrome=87.0.4280.88)

**Comment by AlexFernando001** [comment]
Same issue here :(

**Comment by TobiasPankner** [comment]
Fixed with commit 11f4f7e
