### ISSUE TITLE
Bot won't run

### ISSUE THREAD

**Issue by osophine** [TobiasPankner/Teams-Auto-Joiner#74]
bot will not run. Everything worked well until the final step and it failed as can be seen. What's causing the problem?
Here's everything I typed in and what showed

Microsoft Windows [Version 10.0.19042.746]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\Odera\Downloads\Teams-Auto-Joiner-master\Teams-Auto-Joiner-master>pip install -r requirements.txt
Requirement already satisfied: selenium==3.141.0 in c:\users\odera\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 1)) (3.141.0)
Requirement already satisfied: webdriver_manager==3.2.2 in c:\users\odera\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 2)) (3.2.2)
Requirement already satisfied: msedge-selenium-tools==3.141.3 in c:\users\odera\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 3)) (3.141.3)
Requirement already satisfied: urllib3 in c:\users\odera\appdata\local\programs\python\python39\lib\site-packages (from selenium==3.141.0->-r requirements.txt (line 1)) (1.26.3)
Requirement already satisfied: crayons in c:\users\odera\appdata\local\programs\python\python39\lib\site-packages (from webdriver_manager==3.2.2->-r requirements.txt (line 2)) (0.4.0)
Requirement already satisfied: configparser in c:\users\odera\appdata\local\programs\python\python39\lib\site-packages (from webdriver_manager==3.2.2->-r requirements.txt (line 2)) (5.0.1)
Requirement already satisfied: requests in c:\users\odera\appdata\local\programs\python\python39\lib\site-packages (from webdriver_manager==3.2.2->-r requirements.txt (line 2)) (2.25.1)
Requirement already satisfied: colorama in c:\users\odera\appdata\local\programs\python\python39\lib\site-packages (from crayons->webdriver_manager==3.2.2->-r requirements.txt (line 2)) (0.4.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\odera\appdata\local\programs\python\python39\lib\site-packages (from requests->webdriver_manager==3.2.2->-r requirements.txt (line 2)) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\odera\appdata\local\programs\python\python39\lib\site-packages (from requests->webdriver_manager==3.2.2->-r requirements.txt (line 2)) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\odera\appdata\local\programs\python\python39\lib\site-packages (from requests->webdriver_manager==3.2.2->-r requirements.txt (line 2)) (2020.12.5)
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the 'c:\users\odera\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.

C:\Users\Odera\Downloads\Teams-Auto-Joiner-master\Teams-Auto-Joiner-master>python auto_joiner.py
'reg' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\Odera\Downloads\Teams-Auto-Joiner-master\Teams-Auto-Joiner-master\auto_joiner.py", line 679, in <module>
    main()
  File "C:\Users\Odera\Downloads\Teams-Auto-Joiner-master\Teams-Auto-Joiner-master\auto_joiner.py", line 541, in main
    init_browser()
  File "C:\Users\Odera\Downloads\Teams-Auto-Joiner-master\Teams-Auto-Joiner-master\auto_joiner.py", line 177, in init_browser
    browser = webdriver.Chrome(ChromeDriverManager().install(), options=chrome_options)
  File "C:\Users\Odera\AppData\Local\Programs\Python\Python39\lib\site-packages\webdriver_manager\chrome.py", line 23, in __init__
    self.driver = ChromeDriver(name=name,
  File "C:\Users\Odera\AppData\Local\Programs\Python\Python39\lib\site-packages\webdriver_manager\driver.py", line 54, in __init__
    self.browser_version = chrome_version(chrome_type)
  File "C:\Users\Odera\AppData\Local\Programs\Python\Python39\lib\site-packages\webdriver_manager\utils.py", line 142, in chrome_version
    raise ValueError(f'Could not get version for Chrome with this command: {cmd}')
ValueError: Could not get version for Chrome with this command: reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version

C:\Users\Odera\Downloads\Teams-Auto-Joiner-master\Teams-Auto-Joiner-master>

**Comment by TobiasPankner** [comment]
Do you have Chrome installed?

**Comment by osophine** [comment]
Yes, I have Chrome installed

**Comment by TobiasPankner** [comment]
Take a look at this issue, should be the same way to fix it. https://github.com/TobiasPankner/Teams-Auto-Joiner/issues/9
