### ISSUE TITLE
Unknown Problem

### ISSUE THREAD

**Issue by jxian725** [TobiasPankner/Teams-Auto-Joiner#8]
![image](https://user-images.githubusercontent.com/66273113/89380593-58678900-d72a-11ea-8a76-44f8216f11db.png)
 I got this problem when trying to run it

**Comment by joaoianuci** [comment]
I have that trouble, but in my case I forgot to remove a comma in the last item of the json document.
### BEFORE
`  "headless" : false,
  "mute_audio": true,
  "chrome_type": "google-chrome",`
### AFTER
`  "headless" : false,
  "mute_audio": true,
  "chrome_type": "google-chrome"`

**Comment by jxian725** [comment]
> I have that trouble, but in my case I forgot to remove a comma in the last item of the json document.
> 
> ### BEFORE
> ` "headless" : false, "mute_audio": true, "chrome_type": "google-chrome",`
> 
> ### AFTER
> ` "headless" : false, "mute_audio": true, "chrome_type": "google-chrome"`

Thank you! I just notice i have some syntax error in the config. Fix the syntax then successfully launch
