### ISSUE TITLE
ValueError: Could not get version for Chrome with the command

### ISSUE THREAD

**Issue by Shonty10** [TobiasPankner/Teams-Auto-Joiner#9]
ValueError: Could not get version for Chrome with this command: reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version

Sorry, this may be a simple error but I'm a beginner and do not know how to fix this. It would be very helpful if you can suggest a solution...
https://user-images.githubusercontent.com/69720035/90312854-79e42400-df25-11ea-87f8-8c05afb3c70a.jpg)

**Comment by TobiasPankner** [comment]
Please try deleting this file: USER_HOME/.wdm/drivers.json. Then run it again

**Comment by Shonty10** [comment]
> Please try deleting this file: USER_HOME/.wdm/drivers.json. Then run it again

Unable to locate .wdm folder

**Comment by TobiasPankner** [comment]
It should be in C:/Users/YourUsername/, also make sure that hidden files/folders are visible in explorer

**Comment by Shonty10** [comment]
sure.. will do so n get back to you
