### ISSUE TITLE
JSON decoder error when running app

### ISSUE THREAD

**Issue by kurakensama** [TobiasPankner/Teams-Auto-Joiner#94]
Hi, when running the app this error shows up:

C:\Users\acofre\Downloads\Teams-Auto-Joiner-master\Teams-Auto-Joiner-master>python auto_joiner.py
Traceback (most recent call last):
  File "auto_joiner.py", line 673, in <module>
    load_config()
  File "auto_joiner.py", line 133, in load_config
    config = json.load(json_data_file)
  File "C:\Users\acofre\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\acofre\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\acofre\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\acofre\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

This is my config.json:

{
    "email": "XXXXXXXX@XXXXXX.cl",
    "password": "XXXXXXXXXXXXXX",
    "run_at_time": "09:00",
    "meeting_mode": 1,
    "organisation_num" : 1,
    "random_delay": true,
    "check_interval": 10,
    "join_message": "",
    "auto_leave_after_min": 60,
    "leave_if_last": true,
    "leave_threshold_number": "",
    "leave_threshold_percentage": "",
    "pause_search": false,
    "headless" : false,
    "mute_audio": false,
    "chrome_type": "google-chrome",
    "blacklist": "",
    "blacklist_meeting_re": ""
}

My machine is a Windows 10 Enterprise 2016 LTSB 64 bits. Python 3.7.2 64 bits. And I already checked the config.json with both an online json parser and Liquid Studio.

**Comment by TobiasPankner** [comment]
Try changing it to "blacklist": []

**Comment by TobiasPankner** [comment]
And you renamed the file and didn't move it to another folder?

**Comment by kurakensama** [comment]
Yes

![image](https://user-images.githubusercontent.com/31221983/114090708-c51cbf80-9885-11eb-85cb-777bd9894da9.png)

**Comment by TobiasPankner** [comment]
Very strange. Right now I'm pretty busy.  
I'll look further into it tomorrow or saturday.

**Comment by TobiasPankner** [comment]
I just tried with exact same config.json and it worked fine for me. Do you have experience using a debugger?

**Comment by kurakensama** [comment]
No in Python but I learn fast (I have Python and Visual Studio, could try a few things if you advise me)

**Comment by TobiasPankner** [comment]
Do you have visual studio code or pyCharm?

**Comment by kurakensama** [comment]
I have Visual Studio.

**Comment by kurakensama** [comment]
Both XD

**Comment by TobiasPankner** [comment]
Okay, open the .py file in vscode set a breakpoint at line 131 and click the debug button.  
Then run the script step by step and see what goes wrong.

**Comment by kurakensama** [comment]
Exception has occurred: JSONDecodeError
Expecting value: line 1 column 1 (char 0)
  File "C:\Users\acofre\Downloads\Teams-Auto-Joiner-master\Teams-Auto-Joiner-master\auto_joiner.py", line 133, in load_config
    config = json.load(json_data_file)
  File "C:\Users\acofre\Downloads\Teams-Auto-Joiner-master\Teams-Auto-Joiner-master\auto_joiner.py", line 673, in <module>
    load_config()

I don't get it, at line 1 column 0 I have a {:

![image](https://user-images.githubusercontent.com/31221983/114449128-68314a00-9ba2-11eb-83b4-297bca64c876.png)

**Comment by TobiasPankner** [comment]
Whats the value of json_data_file?

**Comment by kurakensama** [comment]
![image](https://user-images.githubusercontent.com/31221983/114451188-f73f6180-9ba4-11eb-8d97-bcb5ebc2ad04.png)

**Comment by TobiasPankner** [comment]
Okay, try replacing your json file with the  [https://www.github.com/TobiasPankner/Teams-Auto-Joiner/tree/master/config.json.example](example) and try again

**Comment by kurakensama** [comment]
I tried it, again failed. So I checked the encoding, which was UTF-8. I changed it to UTF-8 without BOM, and worked. 

Thank you!

**Comment by TobiasPankner** [comment]
Great!  
I didn't think of that.
