### ISSUE TITLE
Live Caption

### ISSUE THREAD

**Issue by PunchKick** [TobiasPankner/Teams-Auto-Joiner#96]
**Is your feature request related to a problem? Please describe.**
I am using this script for teams meetings, and the organization I work for has a large need for captioning.

**Describe the solution you'd like**
A new Google chrome update released a new feature called Live Captioning. I'd like for that setting to be on by default when I launch my script, so when the script connects to the Teams meeting it also produces caption.

**Describe alternatives you've considered**
I looked into using teams directly, but this script relies on the web version of Teams, which doesn't support captioning.

**Additional context**
This will take you to the feature I am hoping can be used with this script:
chrome://flags/#enable-accessibility-live-captions

**Comment by TobiasPankner** [comment]
Right now, this is not a feature I want to add to the bot as I don't think many people would use it and it increases complexity.  
However, I still found a way to do exactly what you want, just put the code below [line 142](https://github.com/TobiasPankner/Teams-Auto-Joiner/blob/784a5f13f350888a5f97a1ee70f0a865a6b193a7/auto_joiner.py#L162) in the auto_joiner.py file.  
```python
    # turns on live caption
    chrome_options.add_experimental_option("localState", {
        "browser": {
            "enabled_labs_experiments": [
                "enable-accessibility-live-caption@1",
            ]
        }
    })
```

**Comment by PunchKick** [comment]
Thank you so much for your assistance! Could you help me with one more step?

I made the changes you suggested, and the Live Caption setting is now
enabled within Chrome. Would you be able to help me enable the setting
within the accessibility menu? (see below) This setting isn't normally
available until the live caption experimental feature is enabled (which you
solved), but I'm still having trouble figuring out how to enable this
feature after it becomes available.

[image: image.png]

Thanks so much!

-Kurt Abke

**Comment by TobiasPankner** [comment]
The image is not showing up for me, can you try sending it again?

**Comment by PunchKick** [comment]
[image: image.png]

I've attached it again above. Basically it's just a screenshot of the
Caption Preferences & Live Caption setting that you see when you're in
Chrome and you go to Settings->Advanced->Accessibility. However, you will
need the Live Caption setting enabled in Chrome:\\flags to see this setting
within the accessibility menu.

**Comment by TobiasPankner** [comment]
Put the code below after `init_browser()` around line 567.  
```python
    browser.get("chrome://settings/accessibility")
    time.sleep(2)
    browser.execute_script('document.querySelector("body > settings-ui").shadowRoot.querySelector("#main").shadowRoot.querySelector("settings-basic-page").shadowRoot.querySelector("#advancedPage > settings-section:nth-child(5) > settings-a11y-page").shadowRoot.querySelector("#pages > div > settings-toggle-button:nth-child(1)").shadowRoot.querySelector("#control").click();')
    time.sleep(2)
```
This is a extremely hacky solution but it should work.

**Comment by PunchKick** [comment]
You're a legend. Thank you so much!

Do you recommend any learning resources that helped you get to the level
you're at?

**Comment by TobiasPankner** [comment]
You're welcome!  
Sorry but I don't have any learning resources, my advice is to just find something to automate and then tackle it step by step.  
First step would of course be to learn python, from there you can google pretty much everything you need to know.
