### ISSUE TITLE
Some sort of notifications/ saved logs on joined meetings

### ISSUE THREAD

**Issue by Fafera42** [TobiasPankner/Teams-Auto-Joiner#98]
Would love if there would be a chance in the future to see some sort of logging system or even notifications that can be sent to your discord profile via a bot, sometimes I am unsure whether if the bot joined the meetings I had or not so having them logged somewhere in a text document after joining/leaving every meeting with the exact time would be really a nice feature, or even better some sort of notification system that will alert you everytime the bot joined a meeting successfully or not.

**Comment by Ayaan2907** [comment]
Working on this. I had implemented some sort of notification feature for my own project that will work here.

**Comment by Ayaan2907** [comment]
@Fafera42 please assign it to me.

**Comment by Ayaan2907** [comment]
PR #105 is open for this issue.

**Comment by Ayaan2907** [comment]
There are two issues. Raising Both the issues separately will be a better way.
